### PR TITLE
Add support for sending SNS alerts if no YARA rules matched

### PR DESCRIPTION
**Pull request by goochi1**
to: @austinbyers
cc: @airbnb/binaryalert-maintainers
resolves: #104 

## Background

We want the option to send an SNS alert if the file does NOT match any YARA rules

## Changes

Added a new configuration flag, `enable_safe_alerts`, that directs the analyzer to send SNS messages for files which do not match YARA rules

## Testing
tested with and without safe enabled
tested with safe and unsafe files

### CODE REVIEW

**Comment by goochi1** [comment]
@austinbyers  ok updates again :) tested on safe and unsafe files, got sns for both.
tested with enable safe and 1 and 0

**Comment by austinbyers** [comment]
So is this a replacement for #118 ? If so, can you close the other PR?

I'll be out for a few weeks, but I'll be sure to look at it when I get back! Excited to see this move forward

**Comment by goochi1** [comment]
@austinbyers all close, let me know when you get back :) Thanks again

**Comment by austinbyers** [comment]
Hi @goochi1! Yep, I'm still working on some architectural changes, but since you just rebased, I'll go ahead and take a look today

**Comment by goochi1** [comment]
Please tell me you tested it haha

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by austinbyers** [comment]
@goochi1 yes, I did! It works as expected

Before we release v1.2, I'll probably tweak the formatting and language a bit (it's a "negative" alert, not necessarily a "safe" alert). I'll also work on updating the documentation and testing even more rigorously

**Comment by goochi1** [comment]
Of course!! Thanks for approving it!!! Really happy and glad it could help someone else.
Also thanks for your support with it all :)

If you are ever thinking about leaving bnb let me know, I work at KPMG and would love to have you in the team!
Steph

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
